export const africa = [
    { id: 'AO', name: 'Angola' },
    { id: 'BF', name: 'Burkina Faso' },
    { id: 'BI', name: 'Burundi' },
    { id: 'BJ', name: 'Benin' },
    { id: 'BW', name: 'Botswana' },
    { id: 'CD', name: 'Democratic Republic of the Congo' },
    { id: 'CF', name: 'Central African Republic' },
    { id: 'CG', name: 'Republic of the Congo' },
    {
        id: 'CI', name: "Côte d'Ivoire"
    },
    { id: 'CM', name: 'Cameroon' },
    { id: 'DJ', name: 'Djibouti' },
    { id: 'DZ', name: 'Algeria' },
    { id: 'EG', name: 'Egypt' },
    { id: 'ER', name: 'Eritrea' },
    { id: 'ET', name: 'Ethiopia' },
    { id: 'GA', name: 'Gabon' },
    { id: 'GH', name: 'Ghana' },
    { id: 'GM', name: 'Gambia' },
    { id: 'GN', name: 'Guinea' },
    { id: 'GQ', name: 'Equatorial Guinea' },
    { id: 'GW', name: 'Guinea-Bissau' },
    { id: 'KE', name: 'Kenya' },
    { id: 'LR', name: 'Liberia' },
    { id: 'LS', name: 'Lesotho' },
    { id: 'LY', name: 'Libya' },
    { id: 'MA', name: 'Morocco' },
    { id: 'MG', name: 'Madagascar' },
    { id: 'ML', name: 'Mali' },
    { id: 'MR', name: 'Mauritania' },
    { id: 'MW', name: 'Malawi' },
    { id: 'MZ', name: 'Mozambique' },
    { id: 'NA', name: 'Namibia' },
    { id: 'NE', name: 'Niger' },
    { id: 'NG', name: 'Nigeria' },
    { id: 'RW', name: 'Rwanda' },
    { id: 'SD', name: 'Sudan' },
    { id: 'SL', name: 'Sierra Leone' },
    { id: 'SN', name: 'Senegal' },
    { id: 'SO', name: 'Somalia' },
    { id: 'SS', name: 'South Sudan' },
    { id: 'SZ', name: 'Eswatini' },
    { id: 'TD', name: 'Chad' },
    { id: 'TG', name: 'Togo' },
    { id: 'TN', name: 'Tunisia' },
    { id: 'TZ', name: 'Tanzania' },
    { id: 'UG', name: 'Uganda' },
    { id: 'ZA', name: 'South Africa' },
    { id: 'ZM', name: 'Zambia' },
    { id: 'ZW', name: 'Zimbabwe' }
];

export const asia = [
    { id: 'AE', name: 'United Arab Emirates' },
    { id: 'AF', name: 'Afghanistan' },
    { id: 'BD', name: 'Bangladesh' },
    { id: 'BN', name: 'Brunei' },
    { id: 'BT', name: 'Bhutan' },
    { id: 'CN', name: 'China' },
    { id: 'ID', name: 'Indonesia' },
    { id: 'IL', name: 'Israel' },
    { id: 'IN', name: 'India' },
    { id: 'IQ', name: 'Iraq' },
    { id: 'IR', name: 'Iran' },
    { id: 'JO', name: 'Jordan' },
    { id: 'JP', name: 'Japan' },
    { id: 'KG', name: 'Kyrgyzstan' },
    { id: 'KH', name: 'Cambodia' },
    { id: 'KP', name: 'North Korea' },
    { id: 'KR', name: 'South Korea' },
    { id: 'KW', name: 'Kuwait' },
    { id: 'KZ', name: 'Kazakhstan' },
    { id: 'LA', name: 'Laos' },
    { id: 'LB', name: 'Lebanon' },
    { id: 'LK', name: 'Sri Lanka' },
    { id: 'MM', name: 'Myanmar' },
    { id: 'MN', name: 'Mongolia' },
    { id: 'MY', name: 'Malaysia' },
    { id: 'NP', name: 'Nepal' },
    { id: 'OM', name: 'Oman' },
    { id: 'PH', name: 'Philippines' },
    { id: 'PK', name: 'Pakistan' },
    { id: 'PS', name: 'Palestine' },
    { id: 'QA', name: 'Qatar' },
    { id: 'RU-asia', name: 'Russia' },
    { id: 'SA', name: 'Saudi Arabia' },
    { id: 'SY', name: 'Syria' },
    { id: 'TH', name: 'Thailand' },
    { id: 'TJ', name: 'Tajikistan' },
    { id: 'TL', name: 'Timor-Leste' },
    { id: 'TM', name: 'Turkmenistan' },
    { id: 'TW', name: 'Taiwan' },
    { id: 'UZ', name: 'Uzbekistan' },
    { id: 'VN', name: 'Vietnam' },
    { id: 'YE', name: 'Yemen' }
];

export const europe = [
    { id: 'RU', name: 'Russia' },
    // { id: 'GI', name: 'Gibraltar' },
    { id: 'NL', name: 'Netherlands' },
    // { id: 'VA', name: 'Vatican City' },
    { id: 'CY', name: 'Cyprus' },
    { id: 'UA', name: 'Ukraine' },
    { id: 'TR', name: 'Turkey' },
    { id: 'SE', name: 'Sweden' },
    { id: 'SI', name: 'Slovenia' },
    { id: 'SK', name: 'Slovakia' },
    { id: 'RS', name: 'Serbia' },
    { id: 'SM', name: 'San Marino' },
    { id: 'RO', name: 'Romania' },
    { id: 'PT', name: 'Portugal' },
    { id: 'PL', name: 'Poland' },
    { id: 'SJ', name: 'Svalbard and Jan Mayen' },
    { id: 'NO', name: 'Norway' },
    { id: 'ME', name: 'Montenegro' },
    { id: 'MT', name: 'Malta' },
    { id: 'MK', name: 'North Macedonia' },
    { id: 'MD', name: 'Moldova' },
    { id: 'MC', name: 'Monaco' },
    { id: 'LV', name: 'Latvia' },
    { id: 'LU', name: 'Luxembourg' },
    { id: 'LT', name: 'Lithuania' },
    { id: 'LI', name: 'Liechtenstein' },
    { id: 'KV', name: 'Kosovo' },
    { id: 'JE', name: 'Jersey' },
    { id: 'IS', name: 'Iceland' },
    { id: 'IE', name: 'Ireland' },
    { id: 'IM', name: 'Isle of Man' },
    { id: 'HU', name: 'Hungary' },
    { id: 'HR', name: 'Croatia' },
    { id: 'GR', name: 'Greece' },
    { id: 'GG', name: 'Guernsey' },
    { id: 'GE', name: 'Georgia' },
    { id: 'FR', name: 'France' },
    { id: 'FO', name: 'Faroe Islands' },
    { id: 'FI', name: 'Finland' },
    { id: 'EE', name: 'Estonia' },
    { id: 'ES', name: 'Spain' },
    { id: 'GB', name: 'United Kingdom' },
    { id: 'DK', name: 'Denmark' },
    { id: 'DE', name: 'Germany' },
    { id: 'CZ', name: 'Czech Republic' },
    { id: 'CH', name: 'Switzerland' },
    { id: 'BY', name: 'Belarus' },
    { id: 'BA', name: 'Bosnia and Herzegovina' },
    { id: 'BG', name: 'Bulgaria' },
    { id: 'BE', name: 'Belgium' },
    { id: 'AZ', name: 'Azerbaijan' },
    { id: 'AT', name: 'Austria' },
    { id: 'AM', name: 'Armenia' },
    { id: 'AD', name: 'Andorra' },
    { id: 'AX', name: 'Åland Islands' },
    { id: 'AL', name: 'Albania' },
    { id: 'IT', name: 'Italy' },
    { id: 'KZ', name: 'Kazakhstan' }
];

export const middleEast = [
    { id: 'AE', name: 'United Arab Emirates' },
    // { id: 'BH', name: 'Bahrain' },
    { id: 'IL', name: 'Israel' },
    { id: 'IQ', name: 'Iraq' },
    { id: 'IR', name: 'Iran' },
    { id: 'JO', name: 'Jordan' },
    { id: 'KW', name: 'Kuwait' },
    { id: 'LB', name: 'Lebanon' },
    { id: 'OM', name: 'Oman' },
    { id: 'PS', name: 'Palestine' },
    { id: 'QA', name: 'Qatar' },
    { id: 'SA', name: 'Saudi Arabia' },
    { id: 'SY', name: 'Syria' },
    { id: 'YE', name: 'Yemen' }
];

export const northAmerica = [
    { id: 'AG', name: 'Antigua and Barbuda' },
    { id: 'AI', name: 'Anguilla' },
    { id: 'AW', name: 'Aruba' },
    { id: 'BB', name: 'Barbados' },
    { id: 'BL', name: 'Saint Barthélemy' },
    { id: 'BM', name: 'Bermuda' },
    { id: 'BQ', name: 'Bonaire, Sint Eustatius and Saba' },
    { id: 'BS', name: 'Bahamas' },
    { id: 'BZ', name: 'Belize' },
    { id: 'CA', name: 'Canada' },
    { id: 'CR', name: 'Costa Rica' },
    { id: 'CU', name: 'Cuba' },
    { id: 'CW', name: 'Curaçao' },
    { id: 'DM', name: 'Dominica' },
    { id: 'DO', name: 'Dominican Republic' },
    { id: 'GD', name: 'Grenada' },
    { id: 'GL', name: 'Greenland' },
    { id: 'GP', name: 'Guadeloupe' },
    { id: 'GT', name: 'Guatemala' },
    { id: 'HN', name: 'Honduras' },
    { id: 'HT', name: 'Haiti' },
    { id: 'JM', name: 'Jamaica' },
    { id: 'KN', name: 'Saint Kitts and Nevis' },
    { id: 'KY', name: 'Cayman Islands' },
    { id: 'LC', name: 'Saint Lucia' },
    { id: 'MF', name: 'Saint Martin' },
    { id: 'MQ', name: 'Martinique' },
    { id: 'MS', name: 'Montserrat' },
    { id: 'MX', name: 'Mexico' },
    { id: 'NI', name: 'Nicaragua' },
    { id: 'PA', name: 'Panama' },
    { id: 'PM', name: 'Saint Pierre and Miquelon' },
    { id: 'PR', name: 'Puerto Rico' },
    { id: 'SV', name: 'El Salvador' },
    { id: 'SX', name: 'Sint Maarten' },
    { id: 'TC', name: 'Turks and Caicos Islands' },
    { id: 'TT', name: 'Trinidad and Tobago' },
    { id: 'US', name: 'United States' },
    { id: 'VC', name: 'Saint Vincent and the Grenadines' },
    { id: 'VG', name: 'British Virgin Islands' },
    { id: 'VI', name: 'U.S. Virgin Islands' }
];

export const oceania = [
    { id: 'AS', name: 'American Samoa' },
    { id: 'AU', name: 'Australia' },
    { id: 'BN', name: 'Brunei' },
    { id: 'CC', name: 'Cocos (Keeling) Islands' },
    { id: 'CX', name: 'Christmas Island' },
    { id: 'FJ', name: 'Fiji' },
    { id: 'FM', name: 'Micronesia' },
    { id: 'GU', name: 'Guam' },
    { id: 'HM', name: 'Heard Island and McDonald Islands' },
    { id: 'ID', name: 'Indonesia' },
    { id: 'IO', name: 'British Indian Ocean Territory' },
    { id: 'KI', name: 'Kiribati' },
    { id: 'MH', name: 'Marshall Islands' },
    { id: 'MO', name: 'Macau' },
    { id: 'MP', name: 'Northern Mariana Islands' },
    { id: 'NC', name: 'New Caledonia' },
    { id: 'NF', name: 'Norfolk Island' },
    { id: 'NR', name: 'Nauru' },
    { id: 'NU', name: 'Niue' },
    { id: 'NZ', name: 'New Zealand' },
    { id: 'PG', name: 'Papua New Guinea' },
    { id: 'PH', name: 'Philippines' },
    { id: 'PW', name: 'Palau' },
    // { id: 'RE', name: 'Réunion' },
    { id: 'SB', name: 'Solomon Islands' },
    { id: 'SC', name: 'Seychelles' },
    { id: 'SG', name: 'Singapore' },
    // { id: 'TF', name: 'French Southern and Antarctic Lands' },
    { id: 'TK', name: 'Tokelau' },
    { id: 'TL', name: 'Timor-Leste' },
    { id: 'TO', name: 'Tonga' },
    { id: 'TV', name: 'Tuvalu' },
    // { id: 'UM-81', name: 'United States Minor Outlying Islands' },
    // { id: 'UM-84', name: 'United States Minor Outlying Islands' },
    // { id: 'UM-67', name: 'United States Minor Outlying Islands' },
    // { id: 'UM-71', name: 'United States Minor Outlying Islands' },
    // { id: 'UM-79', name: 'United States Minor Outlying Islands' },
    { id: 'VU', name: 'Vanuatu' },
    { id: 'WF', name: 'Wallis and Futuna' },
    { id: 'WS', name: 'Samoa' }
];

export const southAmerica = [
    { id: 'AR', name: 'Argentina' },
    { id: 'BO', name: 'Bolivia' },
    { id: 'BR', name: 'Brazil' },
    { id: 'CL', name: 'Chile' },
    { id: 'CO', name: 'Colombia' },
    { id: 'EC', name: 'Ecuador' },
    { id: 'FK', name: 'Falkland Islands (Malvinas)' },
    { id: 'GF', name: 'French Guiana' },
    { id: 'GY', name: 'Guyana' },
    { id: 'PE', name: 'Peru' },
    { id: 'PY', name: 'Paraguay' },
    { id: 'SR', name: 'Suriname' },
    { id: 'UY', name: 'Uruguay' },
    { id: 'VE', name: 'Venezuela' }
];

export const world = [
    { id: 'AE', name: 'United Arab Emirates' },
    { id: 'AF', name: 'Afghanistan' },
    { id: 'AL', name: 'Albania' },
    { id: 'AM', name: 'Armenia' },
    { id: 'AO', name: 'Angola' },
    { id: 'AR', name: 'Argentina' },
    { id: 'AT', name: 'Austria' },
    { id: 'AU', name: 'Australia' },
    { id: 'AZ', name: 'Azerbaijan' },
    { id: 'BA', name: 'Bosnia and Herzegovina' },
    { id: 'BD', name: 'Bangladesh' },
    { id: 'BE', name: 'Belgium' },
    { id: 'BF', name: 'Burkina Faso' },
    { id: 'BG', name: 'Bulgaria' },
    { id: 'BI', name: 'Burundi' },
    { id: 'BJ', name: 'Benin' },
    { id: 'BN', name: 'Brunei Darussalam' },
    { id: 'BO', name: 'Bolivia' },
    { id: 'BR', name: 'Brazil' },
    { id: 'BS', name: 'Bahamas' },
    { id: 'BT', name: 'Bhutan' },
    { id: 'BW', name: 'Botswana' },
    { id: 'BY', name: 'Belarus' },
    { id: 'BZ', name: 'Belize' },
    { id: 'CA', name: 'Canada' },
    { id: 'CD', name: 'Democratic Republic of the Congo' },
    { id: 'CF', name: 'Central African Republic' },
    { id: 'CG', name: 'Republic of the Congo' },
    { id: 'CH', name: 'Switzerland' },
    { id: 'CI', name: 'Côte d\'Ivoire' },
    { id: 'CL', name: 'Chile' },
    { id: 'CM', name: 'Cameroon' },
    { id: 'CN', name: 'China' },
    { id: 'CO', name: 'Colombia' },
    { id: 'CR', name: 'Costa Rica' },
    { id: 'CU', name: 'Cuba' },
    { id: 'CY', name: 'Cyprus' },
    { id: 'CZ', name: 'Czech Republic' },
    { id: 'DE', name: 'Germany' },
    { id: 'DJ', name: 'Djibouti' },
    { id: 'DK', name: 'Denmark' },
    { id: 'DO', name: 'Dominican Republic' },
    { id: 'DZ', name: 'Algeria' },
    { id: 'EC', name: 'Ecuador' },
    { id: 'EE', name: 'Estonia' },
    { id: 'EG', name: 'Egypt' },
    { id: 'ER', name: 'Eritrea' },
    { id: 'ES', name: 'Spain' },
    { id: 'ET', name: 'Ethiopia' },
    { id: 'FK', name: 'Falkland Islands (Malvinas)' },
    { id: 'FI', name: 'Finland' },
    { id: 'FJ', name: 'Fiji' },
    { id: 'FR', name: 'France' },
    { id: 'GA', name: 'Gabon' },
    { id: 'GB', name: 'United Kingdom' },
    { id: 'GE', name: 'Georgia' },
    { id: 'GF', name: 'French Guiana' },
    { id: 'GH', name: 'Ghana' },
    { id: 'GL', name: 'Greenland' },
    { id: 'GM', name: 'Gambia' },
    { id: 'GN', name: 'Guinea' },
    { id: 'GQ', name: 'Equatorial Guinea' },
    { id: 'GR', name: 'Greece' },
    { id: 'GT', name: 'Guatemala' },
    { id: 'GW', name: 'Guinea-Bissau' },
    { id: 'GY', name: 'Guyana' },
    { id: 'HN', name: 'Honduras' },
    { id: 'HR', name: 'Croatia' },
    { id: 'HT', name: 'Haiti' },
    { id: 'HU', name: 'Hungary' },
    { id: 'ID', name: 'Indonesia' },
    { id: 'IE', name: 'Ireland' },
    { id: 'IL', name: 'Israel' },
    { id: 'IN', name: 'India' },
    { id: 'IQ', name: 'Iraq' },
    { id: 'IR', name: 'Iran' },
    { id: 'IS', name: 'Iceland' },
    { id: 'IT', name: 'Italy' },
    { id: 'JM', name: 'Jamaica' },
    { id: 'JO', name: 'Jordan' },
    { id: 'JP', name: 'Japan' },
    { id: 'KE', name: 'Kenya' },
    { id: 'KG', name: 'Kyrgyzstan' },
    { id: 'KH', name: 'Cambodia' },
    { id: 'KP', name: 'North Korea' },
    { id: 'KR', name: 'South Korea' },
    { id: 'XK', name: 'Kosovo' },
    { id: 'KW', name: 'Kuwait' },
    { id: 'KZ', name: 'Kazakhstan' },
    { id: 'LA', name: 'Laos' },
    { id: 'LB', name: 'Lebanon' },
    { id: 'LK', name: 'Sri Lanka' },
    { id: 'LR', name: 'Liberia' },
    { id: 'LS', name: 'Lesotho' },
    { id: 'LT', name: 'Lithuania' },
    { id: 'LU', name: 'Luxembourg' },
    { id: 'LV', name: 'Latvia' },
    { id: 'LY', name: 'Libya' },
    { id: 'MA', name: 'Morocco' },
    { id: 'MD', name: 'Moldova' },
    { id: 'ME', name: 'Montenegro' },
    { id: 'MG', name: 'Madagascar' },
    { id: 'MK', name: 'North Macedonia' },
    { id: 'ML', name: 'Mali' },
    { id: 'MM', name: 'Myanmar' },
    { id: 'MN', name: 'Mongolia' },
    { id: 'MR', name: 'Mauritania' },
    { id: 'MW', name: 'Malawi' },
    { id: 'MX', name: 'Mexico' },
    { id: 'MY', name: 'Malaysia' },
    { id: 'MZ', name: 'Mozambique' },
    { id: 'NA', name: 'Namibia' },
    { id: 'NC', name: 'New Caledonia' },
    { id: 'NE', name: 'Niger' },
    { id: 'NG', name: 'Nigeria' },
    { id: 'NI', name: 'Nicaragua' },
    { id: 'NL', name: 'Netherlands' },
    { id: 'NO', name: 'Norway' },
    { id: 'NP', name: 'Nepal' },
    { id: 'NZ', name: 'New Zealand' },
    { id: 'OM', name: 'Oman' },
    { id: 'PA', name: 'Panama' },
    { id: 'PE', name: 'Peru' },
    { id: 'PG', name: 'Papua New Guinea' },
    { id: 'PH', name: 'Philippines' },
    { id: 'PK', name: 'Pakistan' },
    { id: 'PL', name: 'Poland' },
    { id: 'PR', name: 'Puerto Rico' },
    { id: 'PS', name: 'Palestine' },
    { id: 'PT', name: 'Portugal' },
    { id: 'PY', name: 'Paraguay' },
    { id: 'QA', name: 'Qatar' },
    { id: 'RO', name: 'Romania' },
    { id: 'RS', name: 'Serbia' },
    { id: 'RU', name: 'Russia' },
    { id: 'RW', name: 'Rwanda' },
    { id: 'SA', name: 'Saudi Arabia' },
    { id: 'SB', name: 'Solomon Islands' },
    { id: 'SD', name: 'Sudan' },
    { id: 'SE', name: 'Sweden' },
    { id: 'SI', name: 'Slovenia' },
    { id: 'SJ', name: 'Svalbard and Jan Mayen' },
    { id: 'SK', name: 'Slovakia' },
    { id: 'SL', name: 'Sierra Leone' },
    { id: 'SN', name: 'Senegal' },
    { id: 'SO', name: 'Somalia' },
    { id: 'SR', name: 'Suriname' },
    { id: 'SS', name: 'South Sudan' },
    { id: 'SV', name: 'El Salvador' },
    { id: 'SY', name: 'Syria' },
    { id: 'SZ', name: 'Eswatini' },
    { id: 'TD', name: 'Chad' },
    { id: 'TF', name: 'French Southern and Antarctic Lands' },
    { id: 'TG', name: 'Togo' },
    { id: 'TH', name: 'Thailand' },
    { id: 'TJ', name: 'Tajikistan' },
    { id: 'TL', name: 'Timor-Leste' },
    { id: 'TM', name: 'Turkmenistan' },
    { id: 'TN', name: 'Tunisia' },
    { id: 'TR', name: 'Turkey' },
    { id: 'TT', name: 'Trinidad and Tobago' },
    { id: 'TW', name: 'Taiwan' },
    { id: 'TZ', name: 'Tanzania' },
    { id: 'UA', name: 'Ukraine' },
    { id: 'UG', name: 'Uganda' },
    { id: 'US', name: 'United States' },
    { id: 'UY', name: 'Uruguay' },
    { id: 'UZ', name: 'Uzbekistan' },
    { id: 'VE', name: 'Venezuela' },
    { id: 'VN', name: 'Vietnam' },
    { id: 'VU', name: 'Vanuatu' },
    { id: 'YE', name: 'Yemen' },
    { id: 'ZA', name: 'South Africa' },
    { id: 'ZM', name: 'Zambia' },
    { id: 'ZW', name: 'Zimbabwe' }
];




